### ISSUE TITLE
$req_method ?

### ISSUE THREAD

**Issue by ghost** [wilforlan/php-framework-tutorial#1]
Have you actually tested it, before making the tutorial.
$req_method is not set and what should we set it to?
If not set, it will always return an error.

**Comment by wilforlan** [comment]
@Critfame this codebase is just a demo and most things are incomplete, you can see a more detailed work in the `part-2` branch

Here is the original framework that has everything

https://github.com/wilforlan/CogentPHP

**Comment by wilforlan** [comment]
Since there is no response, I am assuming its solved. just gonna close this issue
